baseurl: /pcc

exclude:
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
title: Python Crash Course
description: Resources for Python Crash Course, from No Starch Press.
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect